@Host = https://app-spring-programacion2.herokuapp.com

GET {{Host}}/products HTTP/1.1
Accept: application/json

GET {{Host}}/product/3 HTTP/1.1
Accept: application/json

POST {{Host}}/product HTTP/1.1
Content-Type: application/json

{
    "name" : "Prueba5",
    "price": 112.52
}

DELETE {{Host}}/product/5 HTTP/1.1
Accept: application/json

PUT {{Host}}/product HTTP/1.1
Content-Type: application/json

{
    "id" : "5",
    "name" : "Prueba5Cambio",
    "price" : 21.22
}